name: Compress Images
on:
    push:
        branches: [main]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [main]
jobs:
    build:
        name: calibreapp/image-actions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Compress images
              id: calibre
              uses: calibreapp/image-actions@main
              with:
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  compressOnly: true
            - name: Create new pull request if needed
              if: steps.calibre.outputs.markdown != ''
              uses: peter-evans/create-pull-request@v3
              with:
                  title: Compressed images
                  branch-suffix: timestamp
                  commit-message: Compressed images
                  body: ${{ steps.calibre.outputs.markdown }}
